version: '2'

volumes:
  graphql-serie-a-mysql-data:
    driver: local

  graphql-serie-a-redis-data:
    driver: local

services:
  # MySQL 8
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: graphql-serie-a-mysql
    volumes:
      - ./storage/my-custom.cnf:/etc/mysql/conf.d/my-custom.cnf # fix issue with PHP connection
      - graphql-serie-a-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=graphql-serie-a
      - MYSQL_DATABASE=graphql-serie-a
      - MYSQL_USER=graphql-serie-a
      - MYSQL_PASSWORD=graphql-serie-a

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.3-nginx
    container_name: graphql-serie-a-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
      - "443:8083"
    links:
      - mysql
      - cache
      - queue
    environment:
      - XDEBUG_ENABLED=true
      - PHP_IDE_CONFIG=serverName=ambientum

  # Redis
  cache:
    image: redis:4.0
    container_name: graphql-serie-a-redis
    command: --appendonly yes
    volumes:
      - graphql-serie-a-redis-data:/data
    ports:
      - "6379:6379"

  # Laravel Queues
  queue:
    image: ambientum/php:7.3
    container_name: graphql-serie-a-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache
